server:
  # web server domain
  domain: http://localhost:8080
  # web server port
  port: :8086
  # read timeout
  read_timeout: 5s
  # write timeout
  write_timeout: 10s
  # graceful shutdown duration
  graceful_shutdown: 30s
  # debug mode,support local(don't run cron job),dev,pre,prod
  mode: dev
  # white list(0.0.0.0 is allow all)
  whitelist:
    127.0.0.1: true

bot:
  chat_id: 7724638752
  api_key: 8691164628:AAFx41THgAd9zB56OtnJ-pXEWiezlLRCW3U
  base_url: https://api.telegram.org/bot

contract:
  token_address: 0x918F8f8EB8fb8bC43ee7FEaD35a096e6A8F81d6A
  mint_address: 0x326523921a4B1F07b570B59FC782EAeBB292FEa0
  private_key: d712af69c090e5a7f855c9d42561a59aa6461bfae03fd3ac4ff4d9872f2bb461
  chain_id: 11155111