// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

// Injectors from wire.go:

// InitApp 为 wire 注入入口：
// - configPath 由 main 传入
// - 返回 *http.Server，main 自行 ListenAndServe
// func InitApp() *App {
// 	loggerV1 := ioc.InitLogger()
// 	v := ioc.InitGinMiddlewares(loggerV1)
// 	contractHandler := handler.NewContractHandler()
// 	engine := ioc.InitWebServer(v, contractHandler)
// 	botServiceI := service.NewBotService()
// 	token := contract.InitToken()
// 	signer := eip712.NewSigner()
// 	contractServiceI := service2.NewContractService(token, signer)
// 	checkJob := ioc.InitCheckJob(botServiceI, contractServiceI, loggerV1)
// 	cron := ioc.InitJobs(checkJob, loggerV1)
// 	app := &App{
// 		server: engine,
// 		cron:   cron,
// 	}
// 	return app
// }

// // wire.go:

// var ContractSet = wire.NewSet(service2.NewContractService, eip712.NewSigner, contract.InitToken)

// var BotSet = wire.NewSet(service.NewBotService)
