// SPDX-License-Identifier: MIT
pragma solidity ^0.8.19;

import "@openzeppelin/contracts/token/ERC20/IERC20.sol";
import "@openzeppelin/contracts/access/Ownable.sol";
import "@openzeppelin/contracts/utils/cryptography/ECDSA.sol";
import "@openzeppelin/contracts/utils/cryptography/EIP712.sol";
import "@openzeppelin/contracts/utils/ReentrancyGuard.sol";


contract AIBTCMiningRewards is EIP712, Ownable,ReentrancyGuard {
    using ECDSA for bytes32;

    // Token Contract
    IERC20 public immutable token;
    
    // Administrator signature address 
    address public signer;
    
    // The user's existing nonce prevents replay attacks.
    mapping(address => uint256) public nonces;

    mapping(address => uint256 ) public claimAmount;

    uint256 public totalAmount;

    // EIP-712 type hash
    bytes32 private constant CLAIM_TYPEHASH = keccak256(
        "ClaimRequest(address user,uint256 amount,uint256 nonce,uint256 deadline)"
    );

    // event
    event Claimed(address indexed user, uint256 amount, uint256 nonce);
    event SignerUpdated(address indexed oldSigner, address indexed newSigner);
    event TokenUpdated(address indexed oldToken, address indexed newToken);

    constructor(
        address _token,
        address _signer
    ) EIP712("Airdrop", "1") Ownable(msg.sender) {
        token = IERC20(_token);
        signer = _signer;
    }

    /**
     * @notice receive token
     * @param amount Quantity received
     * @param nonce Generated by the backend to prevent replay
     * @param deadline Signature expiration time
     * @param signature Backend administrator's signature
     */
    function claim(
        uint256 amount,
        uint256 nonce,
        uint256 deadline,
        bytes calldata signature
    ) external nonReentrant{    
        // Check invalid amount
        require(amount > 0, "INVALID_AMOUNT");    
        // Check if the signature has expired.
        require(block.timestamp <= deadline, "Signature expired");
        // Check if the nonce is correct.
        require(nonce == nonces[msg.sender], "Invalid nonce");
        // Verify signature
        bytes32 structHash = keccak256(abi.encode(
            CLAIM_TYPEHASH,
            msg.sender,
            amount,
            nonce,
            deadline
        ));
        bytes32 hash = _hashTypedDataV4(structHash);
        address recoveredSigner = hash.recover(signature);
        require(recoveredSigner == signer, "Invalid signature");
        // Marked as claimed
        nonces[msg.sender] = nonce + 1;
        //check balance
        require(token.balanceOf(address(this)) >= amount, "INSUFFICIENT_BALANCE");
        // Transfer Tokens
        require(token.transfer(msg.sender, amount), "Transfer failed");
        totalAmount+=amount;
        claimAmount[msg.sender]+=amount;
        emit Claimed(msg.sender, amount, nonce);
    }

 
    receive() external payable nonReentrant {
        require(msg.value > 0, "NO_BNB");
    }

    /**
     * @notice Update signer address
     */
    function setSigner(address _newSigner) external onlyOwner {
        address oldSigner = signer;
        signer = _newSigner;
        emit SignerUpdated(oldSigner, _newSigner);
    }

    /**
     * @notice Withdraw all tokens (emergency)
     */
    function emergencyWithdraw() external onlyOwner {
        uint256 tokenBalance = token.balanceOf(address(this));
        require(token.transfer(msg.sender, tokenBalance), "Withdraw failed");
    }

     /**
     * @notice token balance
     */
    function balance() external view returns (uint256) {
        return token.balanceOf(address(this));
    }
    function balanceOf(address account) external view returns (uint256){
        return token.balanceOf(account);
    }


}
